import { pgTable, index, uniqueIndex, bigserial, text, timestamp, integer, jsonb, json, uuid, bigint, date, time, boolean } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const waitlist = pgTable("waitlist", {
	id: bigserial({ mode: "bigint" }).primaryKey().notNull(),
	name: text().notNull(),
	phone: text().notNull(),
	lookingFor: text("looking_for").notNull(),
	bioDataFileUrl: text("bio_data_file_url"),
	bioDataFileName: text("bio_data_file_name"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_waitlist_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamp_ops")),
	index("idx_waitlist_looking_for").using("btree", table.lookingFor.asc().nullsLast().op("text_ops")),
	index("idx_waitlist_phone").using("btree", table.phone.asc().nullsLast().op("text_ops")),
	uniqueIndex("ix_waitlist_phone").using("btree", table.phone.asc().nullsLast().op("text_ops")),
]);

export const craftoQuotes = pgTable("crafto_quotes", {
	id: bigserial({ mode: "bigint" }).primaryKey().notNull(),
	text: text(),
	contentType: text("content_type"),
	categoryType: text("category_type"),
	slot: text(),
	url: text(),
	videoUrl: text("video_url"),
	previewImageUrl: text("preview_image_url"),
	stickerUrl: text("sticker_url"),
	nameColor: text("name_color"),
	nameOutlineColor: text("name_outline_color"),
	variantType: text("variant_type"),
	frame: integer(),
	slotRaw: text("slot_raw"),
	sourceCategory: text("source_category"),
	createdBy: text("created_by"),
	quoteCreatorId: text("quote_creator_id"),
	quoteCreatorType: text("quote_creator_type"),
	rawJson: jsonb("raw_json"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_crafto_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamp_ops")),
]);

export const sharechatPosts = pgTable("sharechat_posts", {
	id: bigserial({ mode: "bigint" }).primaryKey().notNull(),
	postId: text("post_id").notNull(),
	postUrl: text("post_url"),
	authorName: text("author_name"),
	authorId: text("author_id"),
	text: text(),
	likes: integer(),
	views: integer(),
	comments: integer(),
	mediaType: text("media_type"),
	mediaUrls: json("media_urls"),
	r2MediaKeys: json("r2_media_keys"),
	hashtags: json(),
	timestamp: timestamp({ mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).notNull(),
}, (table) => [
	index("idx_sharechat_author_timestamp").using("btree", table.authorId.asc().nullsLast().op("text_ops"), table.timestamp.asc().nullsLast().op("timestamp_ops")),
	index("ix_sharechat_posts_author_id").using("btree", table.authorId.asc().nullsLast().op("text_ops")),
	index("ix_sharechat_posts_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamp_ops")),
	index("ix_sharechat_posts_id").using("btree", table.id.asc().nullsLast().op("int8_ops")),
	uniqueIndex("ix_sharechat_posts_post_id").using("btree", table.postId.asc().nullsLast().op("text_ops")),
	index("ix_sharechat_posts_timestamp").using("btree", table.timestamp.asc().nullsLast().op("timestamp_ops")),
]);

export const biodataStandardized = pgTable("biodata_standardized", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	rawBiodataId: bigint("raw_biodata_id", { mode: "number" }),
	name: text().notNull(),
	email: text(),
	age: integer(),
	dateOfBirth: date("date_of_birth"),
	birthTime: time("birth_time"),
	height: text(),
	weight: text(),
	mobileNumber: text("mobile_number"),
	profession: text(),
	education: text(),
	currentLocation: text("current_location"),
	nativePlace: text("native_place"),
	address: text(),
	birthVillage: text("birth_village"),
	birthDistrict: text("birth_district"),
	birthState: text("birth_state"),
	birthPincode: text("birth_pincode"),
	complexion: text(),
	bodyType: text("body_type"),
	bloodGroup: text("blood_group"),
	hobbies: text(),
	interests: text(),
	languages: text(),
	fatherName: text("father_name"),
	motherName: text("mother_name"),
	siblings: text(),
	isVerified: boolean("is_verified").default(false).notNull(),
	verifiedAt: timestamp("verified_at", { mode: 'string' }),
	verifiedBy: text("verified_by"),
	notes: text(),
	sourceFile: text("source_file"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	telegramMessageId: bigint("telegram_message_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	telegramChatId: bigint("telegram_chat_id", { mode: "number" }),
	telegramGroupLabel: text("telegram_group_label"),
	r2MediaKey: text("r2_media_key"),
	r2ParsedKey: text("r2_parsed_key"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_biodata_standardized_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
	index("idx_biodata_standardized_name").using("btree", table.name.asc().nullsLast().op("text_ops")),
	index("idx_biodata_standardized_raw_id").using("btree", table.rawBiodataId.asc().nullsLast().op("int8_ops")),
	index("idx_biodata_standardized_verified").using("btree", table.isVerified.asc().nullsLast().op("bool_ops")),
	uniqueIndex("ix_biodata_standardized_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
]);

export const biodata = pgTable("biodata", {
	id: bigserial({ mode: "bigint" }).primaryKey().notNull(),
	name: text().notNull(),
	email: text(),
	age: integer(),
	dateOfBirth: text("date_of_birth"),
	height: text(),
	mobileNumber: text("mobile_number"),
	profession: text(),
	education: text(),
	address: text(),
	birthPlace: text("birth_place"),
	birthTime: text("birth_time"),
	complexion: text(),
	bodyType: text("body_type"),
	hobbies: text(),
	bloodGroup: text("blood_group"),
	sourceFile: text("source_file"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	telegramMessageId: bigint("telegram_message_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	telegramChatId: bigint("telegram_chat_id", { mode: "number" }),
	telegramGroupLabel: text("telegram_group_label"),
	r2MediaKey: text("r2_media_key"),
	r2ParsedKey: text("r2_parsed_key"),
	createdAt: timestamp("created_at", { mode: 'string' }).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).notNull(),
}, (table) => [
	index("idx_biodata_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
	index("idx_biodata_telegram_message_id").using("btree", table.telegramMessageId.asc().nullsLast().op("int8_ops")),
	uniqueIndex("ix_biodata_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
	index("ix_biodata_id").using("btree", table.id.asc().nullsLast().op("int8_ops")),
	index("ix_biodata_name").using("btree", table.name.asc().nullsLast().op("text_ops")),
	index("ix_biodata_telegram_chat_id").using("btree", table.telegramChatId.asc().nullsLast().op("int8_ops")),
	index("ix_biodata_telegram_message_id").using("btree", table.telegramMessageId.asc().nullsLast().op("int8_ops")),
]);
