/**
 * Subscription Provider Interface
 * 
 * Core interface that all payment providers must implement.
 * Supports both provider-managed and user-managed subscription types.
 */

import type { PaymentProvider } from '../../types/provider.enum';
import type { SubscriptionType } from '../../types/subscription-type.enum';
import type { Subscription, SubscriptionPricing } from '../../domain/entities/subscription.entity';
import type { Order } from '../../domain/entities/order.entity';
import type { BillingFrequency } from '../../types/frequency.enum';

// ============================================================================
// Provider Configuration
// ============================================================================

/**
 * Base provider configuration
 */
export interface ProviderConfig {
  /** Unique configuration ID */
  readonly configId: string;
  /** Provider type */
  readonly provider: PaymentProvider;
  /** App ID this config belongs to */
  readonly appId: string;
  /** Environment */
  readonly environment: 'SANDBOX' | 'PRODUCTION';
  /** Whether this config is enabled */
  readonly enabled: boolean;
  /** Is this the default config for the app */
  readonly isDefault: boolean;
  /** Webhook secret for signature verification */
  readonly webhookSecret: string | null;
}

/**
 * Razorpay-specific configuration
 */
export interface RazorpayProviderConfig extends ProviderConfig {
  readonly provider: 'RAZORPAY';
  readonly keyId: string;
  readonly keySecret: string;
  readonly webhookSecret: string | null;
  readonly accountId: string | null;
}

/**
 * PhonePe-specific configuration
 */
export interface PhonePeProviderConfig extends ProviderConfig {
  readonly provider: 'PHONEPE';
  readonly clientId: string;
  readonly clientSecret: string;
  readonly clientVersion: number;
  readonly merchantId: string;
  readonly saltKey: string | null;
  readonly saltIndex: string | null;
  /** Which PhonePe integration flow to use. Defaults to API_INTEGRATION. */
  readonly checkoutMode?: 'STANDARD_CHECKOUT' | 'API_INTEGRATION';
}

/**
 * Union type for all provider configs
 */
export type AnyProviderConfig = RazorpayProviderConfig | PhonePeProviderConfig;

// ============================================================================
// Setup Subscription Types
// ============================================================================

/**
 * Parameters for setting up a subscription
 */
export interface SetupSubscriptionParams {
  /** Merchant subscription ID (generated by us) */
  readonly merchantSubscriptionId: string;
  /** Merchant order ID for setup payment (generated by us) */
  readonly merchantOrderId: string;
  /** User ID */
  readonly userId: string;
  /** App ID */
  readonly appId: string;
  /** Plan ID (internal) */
  readonly planId: string;
  /** Provider's plan ID */
  readonly providerPlanId: string;
  /** Pricing information */
  readonly pricing: SubscriptionPricing;
  /** Customer email */
  readonly customerEmail: string | null;
  /** Customer phone */
  readonly customerPhone: string | null;
  /** Redirect URL after payment */
  readonly redirectUrl: string | null;
  /** Custom metadata */
  readonly metadata: Record<string, string>;
}

/**
 * Result of subscription setup
 */
export interface SetupSubscriptionResult {
  /** Whether setup was successful */
  readonly success: boolean;
  /** Merchant subscription ID */
  readonly merchantSubscriptionId: string;
  /** Merchant order ID */
  readonly merchantOrderId: string;
  /** Provider's subscription ID */
  readonly providerSubscriptionId: string | null;
  /** Provider's order ID */
  readonly providerOrderId: string;
  /** Payment intent URL (for client-side) */
  readonly intentUrl: string | null;
  /** Redirect URL */
  readonly redirectUrl: string | null;
  /** Order state */
  readonly state: string;
  /** Expiration timestamp */
  readonly expiresAt: Date | null;
  /** Provider-specific data */
  readonly providerData: Record<string, unknown>;
  /** Error message if failed */
  readonly error: string | null;
  /** Error code if failed */
  readonly errorCode: string | null;
}

// ============================================================================
// Charge Subscription Types
// ============================================================================

/**
 * Parameters for charging a subscription
 */
export interface ChargeSubscriptionParams {
  /** Merchant subscription ID */
  readonly merchantSubscriptionId: string;
  /** Provider's subscription ID */
  readonly providerSubscriptionId: string;
  /** Merchant order ID for this charge (generated by us) */
  readonly merchantOrderId: string;
  /** Amount to charge in paise */
  readonly amount: number;
  /** Currency */
  readonly currency: string;
  /** Custom metadata */
  readonly metadata: Record<string, string>;
}

/**
 * Result of subscription charge
 */
export interface ChargeSubscriptionResult {
  /** Whether charge was successful */
  readonly success: boolean;
  /** Merchant order ID */
  readonly merchantOrderId: string;
  /** Provider's order ID */
  readonly providerOrderId: string;
  /** Provider's transaction ID */
  readonly transactionId: string | null;
  /** Amount charged */
  readonly amount: number;
  /** Currency */
  readonly currency: string;
  /** Charge state */
  readonly state: string;
  /** Payment timestamp */
  readonly paidAt: Date | null;
  /** Provider-specific data */
  readonly providerData: Record<string, unknown>;
  /** Error message if failed */
  readonly error: string | null;
  /** Error code if failed */
  readonly errorCode: string | null;
}

// ============================================================================
// Subscription Status Types
// ============================================================================

/**
 * Parameters for checking subscription status
 */
export interface GetSubscriptionStatusParams {
  /** Merchant subscription ID */
  readonly merchantSubscriptionId: string;
  /** Provider's subscription ID */
  readonly providerSubscriptionId: string;
}

/**
 * Result of subscription status check
 */
export interface SubscriptionStatusResult {
  /** Merchant subscription ID */
  readonly merchantSubscriptionId: string;
  /** Provider's subscription ID */
  readonly providerSubscriptionId: string;
  /** Subscription state (provider-specific) */
  readonly providerState: string;
  /** Mapped status (our unified status) */
  readonly mappedStatus: string;
  /** Maximum amount allowed */
  readonly maxAmount: number | null;
  /** Billing frequency */
  readonly frequency: BillingFrequency | null;
  /** Next billing date */
  readonly nextBillingDate: Date | null;
  /** Paid count */
  readonly paidCount: number;
  /** Remaining count */
  readonly remainingCount: number | null;
  /** Whether subscription can be charged */
  readonly canCharge: boolean;
  /** Provider-specific data */
  readonly providerData: Record<string, unknown>;
}

// ============================================================================
// Order Status Types
// ============================================================================

/**
 * Parameters for checking order status
 */
export interface GetOrderStatusParams {
  /** Merchant order ID */
  readonly merchantOrderId: string;
  /** Provider's order ID */
  readonly providerOrderId: string;
}

/**
 * Payment detail from order status
 */
export interface PaymentDetail {
  /** Transaction ID */
  readonly transactionId: string;
  /** Payment mode */
  readonly paymentMode: string | null;
  /** Payment timestamp */
  readonly timestamp: Date;
  /** Amount */
  readonly amount: number;
  /** Payment state */
  readonly state: string;
}

/**
 * Result of order status check
 */
export interface OrderStatusResult {
  /** Merchant order ID */
  readonly merchantOrderId: string;
  /** Provider's order ID */
  readonly providerOrderId: string;
  /** Order state (provider-specific) */
  readonly providerState: string;
  /** Mapped status (our unified status) */
  readonly mappedStatus: string;
  /** Amount */
  readonly amount: number;
  /** Currency */
  readonly currency: string;
  /** Expiration timestamp */
  readonly expiresAt: Date | null;
  /** Payment details */
  readonly paymentDetails: readonly PaymentDetail[];
  /** Provider-specific data */
  readonly providerData: Record<string, unknown>;
}

// ============================================================================
// Webhook Types
// ============================================================================

/**
 * Webhook event parsed from provider
 */
export interface WebhookEvent {
  /** Unique event ID from provider */
  readonly eventId: string;
  /** Event type (provider-specific) */
  readonly eventType: string;
  /** Mapped event type (our unified type) */
  readonly mappedEventType: string;
  /** Payment provider */
  readonly provider: PaymentProvider;
  /** Subscription type */
  readonly subscriptionType: SubscriptionType;
  /** App ID (extracted from webhook) */
  readonly appId: string | null;
  /** Merchant subscription ID */
  readonly merchantSubscriptionId: string | null;
  /** Provider subscription ID */
  readonly providerSubscriptionId: string | null;
  /** Merchant order ID */
  readonly merchantOrderId: string | null;
  /** Provider order ID */
  readonly providerOrderId: string | null;
  /** Payment ID */
  readonly paymentId: string | null;
  /** Event timestamp */
  readonly timestamp: Date;
  /** Event status (from payload) */
  readonly status: string | null;
  /** Amount (from payload) */
  readonly amount: number | null;
  /** Currency */
  readonly currency: string | null;
  /** Raw payload */
  readonly rawPayload: Record<string, unknown>;
  /** Whether signature is valid */
  readonly signatureValid: boolean;
  /** Error code if failed */
  readonly errorCode: string | null;
  /** Error message if failed */
  readonly errorMessage: string | null;
}

/**
 * Parameters for parsing webhook
 */
export interface ParseWebhookParams {
  /** Raw payload (string or object) */
  readonly payload: string | Record<string, unknown>;
  /** Signature header */
  readonly signature: string | null;
  /** All headers */
  readonly headers: Record<string, string>;
}

// ============================================================================
// Cancel Subscription Types
// ============================================================================

/**
 * Parameters for cancelling subscription
 */
export interface CancelSubscriptionParams {
  /** Merchant subscription ID */
  readonly merchantSubscriptionId: string;
  /** Provider's subscription ID */
  readonly providerSubscriptionId: string;
  /** Cancellation reason */
  readonly reason: string | null;
  /** Whether to cancel at the end of current billing cycle (Razorpay-specific) */
  readonly cancelAtCycleEnd?: boolean;
}

/**
 * Result of subscription cancellation
 */
export interface CancelSubscriptionResult {
  /** Whether cancellation was successful */
  readonly success: boolean;
  /** Subscription state after cancellation */
  readonly state: string;
  /** Cancelled at timestamp */
  readonly cancelledAt: Date | null;
  /** Error message if failed */
  readonly error: string | null;
}

// ============================================================================
// Refund Types
// ============================================================================

/**
 * Parameters for refunding payment
 */
export interface RefundPaymentParams {
  /** Provider's payment ID */
  readonly providerPaymentId: string;
  /** Amount to refund (full refund if not specified) */
  readonly amount: number | null;
  /** Refund reason */
  readonly reason: string | null;
  /** Merchant refund ID */
  readonly merchantRefundId: string;
}

/**
 * Result of refund
 */
export interface RefundPaymentResult {
  /** Whether refund was successful */
  readonly success: boolean;
  /** Provider's refund ID */
  readonly refundId: string;
  /** Amount refunded */
  readonly amount: number;
  /** Refund status */
  readonly status: string;
  /** Error message if failed */
  readonly error: string | null;
}

// ============================================================================
// Main Provider Interface
// ============================================================================

/**
 * Subscription provider interface
 * 
 * All providers must implement this interface.
 * The implementation differs based on subscription type:
 * - PROVIDER_MANAGED: Provider handles auto-charging and retries
 * - USER_MANAGED: We initiate charges and handle retries
 */
export interface SubscriptionProvider {
  // === Identity ===
  /** Provider type */
  readonly provider: PaymentProvider;
  /** Subscription type this provider handles */
  readonly subscriptionType: SubscriptionType;

  // === Initialization ===
  /** Initialize provider with configuration */
  initialize(config: AnyProviderConfig): void;
  /** Get public configuration for client-side */
  getPublicConfig(): Record<string, unknown>;

  // === Subscription Lifecycle ===
  /** Setup a new subscription */
  setupSubscription(params: SetupSubscriptionParams): Promise<SetupSubscriptionResult>;
  /** Activate subscription (after mandate approval) */
  activateSubscription?(
    merchantSubscriptionId: string,
    providerSubscriptionId: string,
  ): Promise<SubscriptionStatusResult>;
  /** Cancel subscription */
  cancelSubscription(params: CancelSubscriptionParams): Promise<CancelSubscriptionResult>;
  /** Pause subscription */
  pauseSubscription?(
    merchantSubscriptionId: string,
    providerSubscriptionId: string,
  ): Promise<SubscriptionStatusResult>;
  /** Resume subscription */
  resumeSubscription?(
    merchantSubscriptionId: string,
    providerSubscriptionId: string,
  ): Promise<SubscriptionStatusResult>;
  /** Get subscription status */
  getSubscriptionStatus(params: GetSubscriptionStatusParams): Promise<SubscriptionStatusResult>;

  // === Charging ===
  /** Charge subscription (behavior differs by type) */
  chargeSubscription(params: ChargeSubscriptionParams): Promise<ChargeSubscriptionResult>;
  /** Notify about upcoming charge (PhonePe-specific) */
  notifyCharge?(params: ChargeSubscriptionParams): Promise<ChargeSubscriptionResult>;

  // === Order Management ===
  /** Get order status */
  getOrderStatus(params: GetOrderStatusParams): Promise<OrderStatusResult>;

  // === Refunds ===
  /** Refund a payment */
  refundPayment?(params: RefundPaymentParams): Promise<RefundPaymentResult>;

  // === Webhooks ===
  /** Parse webhook event */
  parseWebhookEvent(params: ParseWebhookParams): Promise<WebhookEvent>;
  /** Verify webhook signature */
  verifyWebhookSignature(
    payload: string | Record<string, unknown>,
    signature: string,
  ): boolean;

  // === Health Check ===
  /** Check provider health */
  healthCheck(): Promise<{ readonly healthy: boolean; readonly message: string | null }>;
}
