"use client";

import Link from "next/link";

export default function AlertSoundboxPrivacyPage() {
  return (
    <section className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
      <div className="flex justify-between items-center mb-6 sm:mb-8">
        <h1 className="text-3xl sm:text-4xl font-medium">Privacy Policy</h1>
        <Link href="/alertpe-soundbox" className="text-gray-600 hover:text-gray-900 text-sm sm:text-base">
          Back to Alert Soundbox
        </Link>
      </div>
      <p className="text-sm text-gray-600 mb-8">Last updated: October 20, 2025</p>

      <div className="space-y-8 text-gray-700">
        <div>
          <p className="text-sm sm:text-base">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="text-sm sm:text-base mt-4">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-medium mb-4">Interpretation and Definitions</h2>
          <h3 className="text-lg sm:text-xl font-medium mb-3">Interpretation</h3>
          <p className="text-sm sm:text-base mb-4">
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="text-lg sm:text-xl font-medium mb-3">Definitions</h3>
          <p className="text-sm sm:text-base mb-3">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside space-y-2 text-sm sm:text-base ml-4">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Application</strong> refers to Alert Soundbox, the software program provided by the Company.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LNPK Business Pvt Ltd.</li>
            <li><strong>Country</strong> refers to: India</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-medium mb-4">Collecting and Using Your Personal Data</h2>
          <h3 className="text-lg sm:text-xl font-medium mb-3">Types of Data Collected</h3>

          <h4 className="text-base sm:text-lg font-medium mb-2">Personal Data</h4>
          <p className="text-sm sm:text-base mb-3">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc list-inside space-y-2 text-sm sm:text-base ml-4 mb-4">
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Usage Data</li>
            <li>Payment notifications: UPI transaction details received via notification access</li>
          </ul>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-medium mb-4">How We Use Your Information</h2>
          <ul className="list-disc list-inside space-y-2 text-sm sm:text-base ml-4">
            <li>Provide voice alerts for UPI payment notifications</li>
            <li>Track daily payment collections</li>
            <li>Improve app functionality and user experience</li>
            <li>Send app updates and important announcements</li>
          </ul>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-medium mb-4">Data Sharing</h2>
          <p className="text-sm sm:text-base">
            We do NOT share your personal information with third parties for marketing purposes. Your data is stored securely on our cloud servers to provide synchronization across devices and backup functionality.
          </p>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-medium mb-4">Data Retention</h2>
          <p className="text-sm sm:text-base">
            Payment notification data and cashbook entries are stored securely on our cloud servers (Firebase). We retain your data for as long as your account is active. You can request data deletion at any time by contacting us at support@kiranaapps.com or by deleting your account through the app settings.
          </p>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-medium mb-4">Data Security</h2>
          <p className="text-sm sm:text-base">
            We implement industry-standard security measures to protect your information. All data is encrypted in transit using SSL/TLS and at rest on our cloud servers. We use Firebase infrastructure which employs enterprise-grade security and regular security audits.
          </p>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-medium mb-4">Permissions Used</h2>
          <ul className="list-disc list-inside space-y-2 text-sm sm:text-base ml-4">
            <li><strong>Notification Access:</strong> Required to read UPI payment notifications and provide voice alerts</li>
            <li><strong>Audio/Media:</strong> Required to play voice alerts for payment notifications</li>
            <li><strong>Storage:</strong> Required to store payment history and app preferences</li>
          </ul>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-medium mb-4">Contact Us</h2>
          <div className="text-sm sm:text-base space-y-1">
            <p><strong>Name:</strong> LNPK Business Pvt Ltd</p>
            <p><strong>Email:</strong> support@kiranaapps.com</p>
            <p><strong>Phone:</strong> +91 8595404595</p>
          </div>
        </div>
      </div>
    </section>
  );
}
