import { ApiProperty } from '@nestjs/swagger';
import { NotificationChannelType } from '../types/notification-event.types';
import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsObject,
  IsEnum,
  IsArray,
} from 'class-validator';

export class NotificationEventDto {
  @ApiProperty({
    example: 'payment.received',
    required: false,
    description: 'Optional event identifier generated by client',
  })
  @IsString()
  @IsOptional()
  eventId?: string;

  @ApiProperty({
    example: 'payment.received',
    description: 'Event type for routing/processing',
  })
  @IsString()
  @IsNotEmpty()
  eventType!: string;

  // NOTE: appId is NOT accepted from request body for security reasons.
  // It is always taken from the X-App-ID header (validated by AppIdGuard).

  @ApiProperty({
    example: {
      amount: 1500,
      currency: 'INR',
      senderName: 'Amit Sharma',
      referenceId: 'UPI-12345',
    },
    required: false,
    description: 'Event payload for downstream consumers',
  })
  @IsObject()
  @IsOptional()
  payload?: Record<string, unknown>;

  @ApiProperty({
    example: [NotificationChannelType.Sms, NotificationChannelType.Push],
    enum: NotificationChannelType,
    required: false,
    description: 'Delivery channels for the event',
  })
  @IsArray()
  @IsEnum(NotificationChannelType, { each: true })
  @IsOptional()
  channels?: NotificationChannelType[];

  @ApiProperty({
    example: { source: 'test-script', priority: 'high' },
    required: false,
    description: 'Optional metadata for debugging or routing',
  })
  @IsObject()
  @IsOptional()
  metadata?: Record<string, unknown>;
}
